baseURL = 'https://warrenu.github.io'
languageCode = 'en-us'
title = "Warren's Blog"
theme = "hugo-blog-awesome"
enableEmoji = true

[menu]
  # [[menu.main]]
  # identifier = "resume"
  # name = "Resume"
  # url = "/resume/"  # Point to a custom page
  # weight = 10

  [[menu.main]]
  name = "Blog Posts"
  url = "/posts/"
  weight = 1

  [[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 1

[[params.socialIcons]]
name = "github"
url = "https://github.com/warrenu"

[params]
  author.name = "Warren U"
  author.avatar = "images/avatar.jpg"
  author.intro = "Hi, I'm Warren"
  author.description = "A Software Engineer who loves working on systems that grow with users' needs. I thrive in collaborative environments, enjoy learning from others, and get energy from tackling tough challenges that push me to improve."
  goToTop = true

  # Projects configuration
  [[params.projects]]
  name = "Pokemon Card Viewer"
  description = "React project, in AWS S3 that allows you to look up and view pokemon cards."
  github = "https://github.com/warrenu/pokemon-card-viewer"
  terraform = "https://github.com/warrenu/pokemon-card-viewer-terraform"
  demo = "http://pokemon-card-viewer-an8g8rr7.s3-website-us-east-1.amazonaws.com"


[home]
  Title = "Recent Posts"

[markup]
  [markup.highlight]
    style = "monokai"  # Choose a style that suits your theme (e.g., "monokai", "solarized-dark", "dracula")
    codeFences = true  # Enables fenced code blocks
    lineNumbers = true  # Optional: Adds line numbers to the code blocks